# Generated by Django 4.1.5 on 2023-02-22 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=10)),
                ('requestedrole', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 2, 22, 4, 37, 25, 494843))),
                ('status', models.CharField(default='Pending', max_length=25)),
            ],
        ),
    ]
