# Generated by Django 4.1.5 on 2023-02-23 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 4, 54, 22, 488418)),
        ),
    ]
