# Generated by Django 4.1.5 on 2023-02-23 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_alter_consentrequest_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrequest',
            name='consentid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='consentrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 5, 59, 40, 358430)),
        ),
    ]
