# Generated by Django 4.1.5 on 2023-02-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0005_remove_consentrequest_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrequest',
            name='patientid',
            field=models.CharField(max_length=50),
        ),
    ]
